<a href="https://colab.research.google.com/github/harmanbajwa2954/python_practice/blob/main/Numpy_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**

In [ ]:
import numpy as np

In [ ]:
arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
arr.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
#linespace
arr1 = np.linspace(1,10,10)
arr1

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
#trignometry
arr2 = np.array([0,30,45,60,90])
nsin = np.sin(arr2)
print(nsin)

ncos = np.cos(arr2)
print(ncos)

[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]
[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]


In [ ]:
#arrange
nn5 = np.random.randint(1,5,10)
nn5
print(np.size(nn5))

10


In [ ]:
#to define an empty array
nn = np.empty(len(nn5))

In [ ]:
#create method to populate array of n elements and return array of reciprocal

def recip(n):
  arr = np.random.randint(1,100,n)
  print(f'The Original Array : {arr}')
  for i in range(n):
    arr1[i] = 1/arr[i]
  return arr1



n = int(input("Enter number : "))
recip(n)

Enter number : 10
The Original Array : [ 6 69 51 40  6 39 49 93 51 47]


array([0.16666667, 0.01449275, 0.01960784, 0.025     , 0.16666667,
       0.02564103, 0.02040816, 0.01075269, 0.01960784, 0.0212766 ])

In [ ]:
#Universal functions
# sin cos exponential sqrt square log log10, log2, log1p sign ceil floor rint modf isnan
#Binary Universal Functions

In [ ]:
n1 = np.arange(1,26).reshape(5,5)
print(n1)
n1[1::2,::2]


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[ 6,  8, 10],
       [16, 18, 20]])

In [ ]:
#program to convert km to miles
km = int(input("Enter the value in Kilometer : "))
miles = km* 0.621371
print("Miles : ", miles)

Enter the value in Kilometer : 130
Miles :  80.77823000000001


In [ ]:
#program to print whole month
import calendar


In [ ]:
year = int(input("Enter year : "))
month = int(input("Enter the month : "))
cal = calendar.month(year,month)
print(cal)

Enter year : 2026
Enter the month : 2
   February 2026
Mo Tu We Th Fr Sa Su
                   1
 2  3  4  5  6  7  8
 9 10 11 12 13 14 15
16 17 18 19 20 21 22
23 24 25 26 27 28



In [ ]:
#program to solve quadratic equation
a = float(input("Enter coefficeant of x^2 : "))
b = float(input("Enter coefficient of x : "))
c = float(input("Constant value c : "))
dis = (b**2) - (4*a*c)
if(dis < 0):
  print("No real roots for the equation.")
else:
  x1 = (-b + (dis**0.5))/(2*a)
  x2 = (-b - (dis**0.5))/(2*a)
  print(f"The roots of equation are {x1} and {x2}")

Enter coefficeant of x^2 : 1
Enter coefficient of x : -2
Constant value c : 1
The roots of equation are 1.0 and 1.0


In [ ]:
#fibonacci series
n = int(input("Enter the no. of terms to print : "))
n1, n2 = 0, 1
for i in range(1, n):
  print(n1,end =" ")
  n1 , n2 = n2 , n2+n1

Enter the no. of terms to print : 10
0 1 1 2 3 5 8 13 21 

In [ ]:
#armstrong number
#a number is armstrong if sum of its digits raised to power of no. of digits

arm = int(input("Enter the number to check : "))
arm_digit = len(str(arm))
temp = arm
sum_of_powers = 0

while temp > 0:
  digit = temp%10
  sum_of_powers += digit ** arm_digit
  temp //= 10

if(sum_of_powers == arm ):
  print('Its is an armstrong number')
else:
  print('It is not an armstrong number')

Enter the number to check : 153
Its is an armstrong number


# **PANDAS**


In [ ]:
# Pandas
import pandas as pd

data = {
    'name' : ['Jane', 'Reze', 'Dense', 'Nigga'],
    'age': [21, 23,12,45, ],
    'city':['LA','Port','Berlin','Kyoto'],
    'salary' :[23000, 14900, 45080, 35700]
}
df = pd.DataFrame(data)
print(df)


    name  age    city  salary
0   Jane   21      LA   23000
1   Reze   23    Port   14900
2  Dense   12  Berlin   45080
3  Nigga   45   Kyoto   35700


In [ ]:
#basic operations on pandas
df.head() #displays first 5 rows for default or N rows for given parameter df.head(N)
df.tail()

name  age    city  salary
0   Jane   21      LA   23000
1   Reze   23    Port   14900
2  Dense   12  Berlin   45080
3  Nigga   45   Kyoto   35700

In [ ]:
df.describe()

age        salary
count   4.000000      4.000000
mean   25.250000  29670.000000
std    14.008926  13372.494158
min    12.000000  14900.000000
25%    18.750000  20975.000000
50%    22.000000  29350.000000
75%    28.500000  38045.000000
max    45.000000  45080.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    4 non-null      object
 1   age     4 non-null      int64 
 2   city    4 non-null      object
 3   salary  4 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes


In [ ]:
#loading a data set from a csv

df1 = pd.read_csv('/content/sample_data/california_housing_train.csv')

df1

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
0          1015.0       472.0         1.4936             66900.0  
1          1129.0       463.0         1.8200             80100.0  
2           333.0       117.0         1.6509             85700.0  
3           515.0       226.0         3.1917             73400.0  
4           624.0       262.0         1.9250             65500.0  
...           ...         ...            ...                 ...  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0  

[17000 rows x 9 columns]

In [ ]:
df1.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

**RANDOM module**

Using random.seed()

In [ ]:
import random
for i in range(2):
    print(random.randint(1, 1000))

for i in range(2):
    random.seed(1) #
    print(random.randint(1, 1000))

395
777
138
138


*Notice that generating random numbers without using the .seed() method results in different outputs on each run, whereas using it ensures consistent results every time.*

random.randint(start,stop)
generates random integers

TO generate an array of random numbers

In [ ]:
arr = random.randint()